// packages/svelte-view360/demo/pano/Video.svelte
<script lang="ts">
  import PanoViewer from "../../src/PanoViewer";

  let pano: PanoViewer;
  let overlay = true;
  let children = [0, 1, 2, 3, 4];

  function addChild() {
    const last = children[children.length - 1];
    children = [...children, last + 1, last + 2];
  }

  function play() {
    pano.getVideo().play();

    overlay = false;
  }
</script>

<button on:click={addChild}>Increase Children</button>
<PanoViewer
  class="viewer"
  bind:this={pano}
  video="https://naver.github.io/egjs-view360/examples/img/equi.mp4"
>
  <div class="overlay" on:click={play} class:hidden={ !overlay }>
    Click to play
  </div>
  {#each children as item, index}
    <li>{index + 1}: {item}</li>
  {/each}
</PanoViewer>

// packages/react-view360/demo/pano/Video.tsx
import React from "react";
import { PanoViewer } from "src/index";

export default class RerenderVideo extends React.Component<{}, { overlay: boolean }> {
  private _panoViewer: PanoViewer;

  public constructor(props) {
    super(props);

    this.state = {
      overlay: true
    }
  }

  public render() {
    return <div>
      <h1>Video</h1>
      <button onClick={() => { this.forceUpdate(); }}>Force Update</button>
      <PanoViewer ref={ref => {
        ref && (this._panoViewer = ref);
      }} id="viewer"
        video={"https://naver.github.io/egjs-view360/examples/img/equi.mp4"}
      >
        <div className={`overlay${this.state.overlay ? "" : " hidden"}`}
          onClick={() => {
            if (!this._panoViewer) return;

            this._panoViewer.getVideo().play();
            this.setState({
              overlay: false
            });
          }}
        >Click to play</div>
      </PanoViewer>
    </div>
  }
}
