// packages/react-view360/demo/pano/Video.tsx
import React from "react";
import { PanoViewer } from "src/index";

export default class RerenderVideo extends React.Component<{}, { overlay: boolean }> {
  private _panoViewer: PanoViewer;

  public constructor(props) {
    super(props);

    this.state = {
      overlay: true
    }
  }

  public render() {
    return <div>
      <h1>Video</h1>
      <button onClick={() => { this.forceUpdate(); }}>Force Update</button>
      <PanoViewer ref={ref => {
        ref && (this._panoViewer = ref);
      }} id="viewer"
        video={"https://naver.github.io/egjs-view360/examples/img/equi.mp4"}
      >
        <div className={`overlay${this.state.overlay ? "" : " hidden"}`}
          onClick={() => {
            if (!this._panoViewer) return;

            this._panoViewer.getVideo().play();
            this.setState({
              overlay: false
            });
          }}
        >Click to play</div>
      </PanoViewer>
    </div>
  }
}

// packages/ngx-view360/projects/demo/src/app/video/video.component.ts
import { ChangeDetectorRef, Component, ViewChild } from "@angular/core";

@Component({
  selector: "demo-video",
  templateUrl: "./video.component.html",
  styleUrls: ["../app.component.css", "./video.component.css"]
})
export class VideoComponent {
  public overlayHidden = false;
  public refresher: string = "";

  public get overlayClass() { return this.overlayHidden ? "overlay hidden" : "overlay"; }

  @ViewChild("pano") public panoViewer;

  public constructor(private _cdr: ChangeDetectorRef) { }

  public forceUpdate() {
    this.refresher = "SOME_TEMP_VALUE";
    this._cdr.detectChanges();
    this.refresher = "";
  }

  public startVideo() {
    if (!this.panoViewer) return;

    this.panoViewer.getVideo().play();
    this.overlayHidden = true;
  }
}

<div>
  <button (click)="forceUpdate()">Force Update</button>
  <ngx-pano-viewer
    #pano
    id="viewer"
    [video]="'https://naver.github.io/egjs-view360/examples/img/equi.mp4'"
  >
  <div
    [ngClass]="overlayClass"
    (click)="startVideo()"
  >Click to play</div>
  </ngx-pano-viewer>
</div>
