// packages/svelte-view360/demo/spin/Spin.svelte
<script lang="ts">
let viewer: SpinViewer;
let scale = 1;

function spin() {
  viewer.spinBy(720, { duration: 500 });
}

function changeScale() {
  scale = scale === 1 ? 5 : 1;
}
</script>
<SpinViewer
  id="spin"
  bind:this={viewer}
  imageUrl="https://naver.github.io/egjs-view360/common/img/spinviewer/spin_demo.jpg"
  rowCount={47}
  wrapperClass="im-wrapper"
  imageClass="im-image"
  scale={scale}
/>
<button on:click={spin}>spin</button>
<button on:click={changeScale}>change scale</button>

// packages/ngx-view360/projects/demo/src/app/spin/spin.component.ts
import { ChangeDetectorRef, Component, ViewChild } from "@angular/core";

@Component({
  selector: "demo-spin",
  templateUrl: "./spin.component.html",
  styleUrls: ["../app.component.css", "./spin.component.css"]
})
export class SpinComponent {
  public refresher: string = "";

  @ViewChild("viewer") public spinViewer;

  public constructor(private _cdr: ChangeDetectorRef) { }

  public forceUpdate() {
    this.refresher = "SOME_TEMP_VALUE";
    this._cdr.detectChanges();
    this.refresher = "";
  }

  public spinBy() {
    if (!this.spinViewer) return;

    this.spinViewer.spinBy(720, { duration: 500 });
  }

  public onLoad(evt) {
    console.log(evt);
  }
}

<div>
  <button (click)="forceUpdate()">Force Update</button>
  <ngx-spin-viewer
    #viewer
    id="spin"
    [imageUrl]="'https://naver.github.io/egjs-view360/common/img/spinviewer/spin_demo.jpg'"
    [rowCount]="47"
    [scale]="1"
    (load)="onLoad($event)"
  ></ngx-spin-viewer>
  <button (click)="spinBy()">spin</button>
</div>
